title: JKW Notes
email: jkw5022@cafe24.com

github_username:  2349
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: pygments
permalink: /:categories/:year/:month/:day/:title/

safe: true
lsi: true
baseurl: /jkw
gems:
  - jekyll-redirect-from
  - jemoji
encoding: "utf-8"
paginate: 15