title: JKW blog
markdown: kramdown
highlighter: pygments
permalink: /:categories/:year/:month/:day/:title/
excerpt_separator: ""
collections:
  docs:
    output: true
name: jkw blog
description: jkw blog
baseurl: /jkw
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
encoding: "utf-8"
paginate: 10
paginate_path: "/blog/page:num/"